create table if not exists public.pending_registrations (
  id text primary key,
  name text not null,
  email text not null unique,
  phone text,
  password text not null,
  role text not null check (role in ('treinador', 'atleta')),
  modality text,
  experience text,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.password_reset_requests (
  id text primary key,
  email text not null,
  user_id text not null,
  user_name text not null,
  role text not null check (role in ('treinador', 'atleta')),
  status text not null default 'pendente' check (status in ('pendente', 'resolvido', 'rejeitado')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.notifications (
  id text primary key,
  user_id text not null,
  title text not null,
  message text not null,
  type text not null check (type in ('warning', 'info', 'success', 'error')),
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.academias (
  id bigint generated by default as identity primary key,
  nome text not null,
  localizacao text,
  telefone text,
  status text not null default 'ativa',
  created_at timestamptz not null default now()
);

create table if not exists public.pagamentos (
  id bigint generated by default as identity primary key,
  membro_id bigint,
  membro_nome text,
  valor numeric not null default 0,
  status text not null default 'pendente' check (status in ('pago', 'pendente', 'atrasado')),
  data_pagamento date,
  created_at timestamptz not null default now()
);

create table if not exists public.recibos_pagamentos (
  id bigint generated by default as identity primary key,
  pagamento_id bigint,
  membro_id bigint,
  membro_nome text,
  valor numeric,
  arquivo_url text,
  arquivo_nome text,
  status text not null default 'pendente' check (status in ('pendente', 'aprovado', 'rejeitado')),
  created_at timestamptz not null default now()
);

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text not null default 'outro',
  quantidade integer not null default 0,
  quantidade_minima integer not null default 0,
  unidade text not null default 'unidade',
  preco numeric not null default 0,
  imagem_url text,
  fornecedor text,
  created_at timestamptz not null default now()
);

create table if not exists public.movimentos_estoque (
  id bigint generated by default as identity primary key,
  produto_id bigint,
  tipo text not null check (tipo in ('entrada', 'saida')),
  quantidade integer not null default 0,
  motivo text,
  user_id text,
  created_at timestamptz not null default now()
);

alter table public.usuarios
add column if not exists senha text,
add column if not exists approval_status text not null default 'aprovado',
add column if not exists academia_id bigint references public.academias(id);

alter table public.membros
add column if not exists senha text,
add column if not exists approval_status text not null default 'aprovado',
add column if not exists academia_id bigint references public.academias(id);

alter table public.treinos
add column if not exists academia_id bigint references public.academias(id);

alter table public.pagamentos
add column if not exists academia_id bigint references public.academias(id);

alter table public.produtos
add column if not exists academia_id bigint references public.academias(id),
add column if not exists imagem_url text;

insert into public.academias (id, nome, localizacao, telefone, status)
select 1, 'Academia Principal', '', '', 'ativa'
where not exists (
  select 1
  from public.academias
  where id = 1
);

update public.usuarios
set academia_id = 1
where academia_id is null;

update public.membros
set academia_id = 1
where academia_id is null;

update public.treinos
set academia_id = 1
where academia_id is null;

update public.pagamentos
set academia_id = 1
where academia_id is null;

update public.produtos
set academia_id = 1
where academia_id is null;

insert into public.usuarios (
  id,
  nome,
  email,
  telefone,
  role,
  senha,
  status,
  approval_status
)
select
  1000000001,
  'Gestor MagManage',
  'gestor@magmanage.com',
  '',
  'gestor',
  'admin123',
  'ativo',
  'aprovado'
where not exists (
  select 1
  from public.usuarios
  where lower(email) = 'gestor@magmanage.com'
);

update public.usuarios
set senha = 'admin123'
where lower(email) = 'gestor@magmanage.com'
  and (senha is null or senha = '');

update public.usuarios
set senha = 'treino123'
where lower(email) = 'treinador@magmanage.com'
  and (senha is null or senha = '');

update public.membros
set senha = 'atleta123'
where lower(email) = 'atleta@magmanage.com'
  and (senha is null or senha = '');

update public.usuarios
set role = 'gestor',
    status = coalesce(status, 'ativo'),
    approval_status = 'aprovado'
where lower(email) = 'gestor@magmanage.com';

alter table public.usuarios enable row level security;
alter table public.membros enable row level security;
alter table public.academias enable row level security;
alter table public.pending_registrations enable row level security;
alter table public.password_reset_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.pagamentos enable row level security;
alter table public.recibos_pagamentos enable row level security;
alter table public.produtos enable row level security;
alter table public.movimentos_estoque enable row level security;

drop policy if exists "Permitir tudo usuarios" on public.usuarios;
create policy "Permitir tudo usuarios"
on public.usuarios
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo membros" on public.membros;
create policy "Permitir tudo membros"
on public.membros
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo academias" on public.academias;
create policy "Permitir tudo academias"
on public.academias
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo pending_registrations" on public.pending_registrations;
create policy "Permitir tudo pending_registrations"
on public.pending_registrations
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo password_reset_requests" on public.password_reset_requests;
create policy "Permitir tudo password_reset_requests"
on public.password_reset_requests
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo notifications" on public.notifications;
create policy "Permitir tudo notifications"
on public.notifications
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo pagamentos" on public.pagamentos;
create policy "Permitir tudo pagamentos"
on public.pagamentos
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo recibos_pagamentos" on public.recibos_pagamentos;
create policy "Permitir tudo recibos_pagamentos"
on public.recibos_pagamentos
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo produtos" on public.produtos;
create policy "Permitir tudo produtos"
on public.produtos
for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir tudo movimentos_estoque" on public.movimentos_estoque;
create policy "Permitir tudo movimentos_estoque"
on public.movimentos_estoque
for all
to anon
using (true)
with check (true);
